databases:
  - name: ethscriptions-db
    plan: standard

services:
  - name: ethscriptions-api
    type: web
    runtime: ruby
    plan: starter
    buildCommand: "bundle install"
    preDeployCommand: "bundle exec rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: "/up"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethscriptions-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "2"
      - key: RAILS_MAX_THREADS
        value: "5"
      - key: ETHEREUM_CLIENT_CLASS
        value: AlchemyClient
      - key: ETHEREUM_CLIENT_BASE_URL
        value: https://eth-mainnet.g.alchemy.com/v2
      - key: ETHEREUM_CLIENT_API_KEY
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_BASE_URL
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_KEY
        sync: false
      - key: ETHEREUM_NETWORK
        value: eth-mainnet
      - key: BLOCK_IMPORT_BATCH_SIZE
        value: "2"
      - key: TESTNET_START_BLOCK
        sync: false

  - name: ethscriptions-indexer
    type: worker
    runtime: ruby
    plan: starter
    buildCommand: "bundle install"
    startCommand: "bundle exec clockwork config/main_importer_clock.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethscriptions-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: ETHEREUM_CLIENT_CLASS
        value: AlchemyClient
      - key: ETHEREUM_CLIENT_BASE_URL
        value: https://eth-mainnet.g.alchemy.com/v2
      - key: ETHEREUM_CLIENT_API_KEY
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_BASE_URL
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_KEY
        sync: false
      - key: ETHEREUM_NETWORK
        value: eth-mainnet
      - key: BLOCK_IMPORT_BATCH_SIZE
        value: "2"
      - key: TESTNET_START_BLOCK
        sync: false