version: "1"

envVarGroups:
  - name: rails-common
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
  - name: app-common
    envVars:
      - key: ETHEREUM_CLIENT_CLASS
        value: AlchemyClient
      - key: ETHEREUM_CLIENT_BASE_URL
        value: https://eth-mainnet.g.alchemy.com/v2
      - key: ETHEREUM_NETWORK
        value: eth-mainnet
      - key: BLOCK_IMPORT_BATCH_SIZE
        value: "2"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: RAILS_MAX_THREADS
        value: "5"

services:
  - name: ethscriptions-api
    type: web
    runtime: ruby
    plan: free
    branch: alt
    region: oregon
    buildCommand: "bundle install && bundle exec rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: "/up"
    envVars:
      - fromGroup: rails-common
      - fromGroup: app-common
      - key: DATABASE_URL
        fromDatabase:
          name: ethscriptions-db
          property: connectionString
      - key: ETHEREUM_CLIENT_API_KEY
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_BASE_URL
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_KEY
        sync: false
      - key: TESTNET_START_BLOCK
        sync: false

  - name: ethscriptions-indexer
    type: worker
    runtime: ruby
    plan: free
    branch: alt
    region: oregon
    buildCommand: "bundle install && bundle exec rake db:migrate"
    startCommand: "bundle exec clockwork config/main_importer_clock.rb"
    envVars:
      - fromGroup: rails-common
      - fromGroup: app-common
      - key: DATABASE_URL
        fromDatabase:
          name: ethscriptions-db
          property: connectionString
      - key: ETHEREUM_CLIENT_API_KEY
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_BASE_URL
        sync: false
      - key: ETHEREUM_BEACON_NODE_API_KEY
        sync: false
      - key: TESTNET_START_BLOCK
        sync: false

databases:
  - name: ethscriptions-db
    plan: basic-256mb
